# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ece223ea4ec5f764d2cb1618debcf07b18d28003dbf326d82c927ee0f57726952f3567ea91661469e73b90e63da9e6bb9a8c756d17b24e3a3b20f428524e50e

test:
  secret_key_base: 7711be06b440a04a1167de6d2081eafad878f946403882e6a7d5b3d7311792749e5bc4a8be760cc962c416e56587fee8e6d021286c141c7d1273953ae688a0eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
