# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa0a40a4345ebea6cc9c8e31bd57c88ec1d07ba64f8df3db4c64b5e0ee779bd553ea8b32cff5717b44c80911a122a1b870686fff3bbc850ebfdd126ee23503d

test:
  secret_key_base: 7ae3e2211387564c8abb01c577bc00e83e5d429bac681a2d9331b861b2c1e2402ff067218fd4d83055717a3360d388a64b8d246b8cdfcca8c6321d78e58428bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
